FROM python:3.10-slim

WORKDIR /app

# Install system build dependencies for pefile and yara
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libmagic1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "python seed.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
